const questionsDatabase = {
    server: [
        {id:1,type:"multiple",question:"Что такое DM (DeathMatch)?",options:["Убийство без IC-причины","NonRP вождение","Уход в AFK","Нарушение чата"],correct:0,ruleNumber:"2.19",ruleFull:"Запрещён DM (DeathMatch) — убийство без веской IC-причины — | Jail 90 минут",punishment:"Jail 90 минут",hint:"Это убийство без причины"},
        {id:2,type:"text",question:"Какое наказание за DM?",correctAnswers:["jail 90","90 минут","jail 90 минут"],ruleNumber:"2.19",ruleFull:"Запрещён DM — | Jail 90 минут",hint:"Тяжелое нарушение"},
        {id:3,type:"multiple",question:"Что такое DB (DriveBy)?",options:["Убийство из машины","Быстрая езда","Читы","Флуд в чате"],correct:0,ruleNumber:"2.13",ruleFull:"Запрещён DB (DriveBy) — намеренное убийство из транспорта без IC причины",punishment:"Warn",hint:"Это убийство машиной"},
        {id:4,type:"multiple",question:"Что означает SK (SpawnKill)?",options:["Убийство при спавне на территории","Убийство в семье","Убийство в VIP зоне","Убийство ночью"],correct:0,ruleNumber:"2.16",ruleFull:"Запрещён SK (Spawn Kill) — убийство на территории фракции при спавне",punishment:"Warn",hint:"Spawn - появление"},
        {id:5,type:"text",question:"Наказание за TK (TeamKill)?",correctAnswers:["warn","варн","варни"],ruleNumber:"2.15",ruleFull:"Запрещён TK (Team Kill) — убийство союзников — | Warn",hint:"Убийство своих товарищей"},
        {id:6,type:"multiple",question:"Что такое MG (MetaGaming)?",options:["Использование OOC информации в IC","Быстрое передвижение","Использование читов","Оскорбление в чате"],correct:0,ruleNumber:"2.18",ruleFull:"Запрещён MG (MetaGaming) — использование OOC информации в IC",punishment:"Ban 15-30 дней",hint:"Информация из реальной жизни"},
        {id:7,type:"punishment",question:"За какое нарушение Jail 120 минут?",options:["Jail","Mute","Ban","Warn"],correctPunishments:["Jail"],additionalText:"120 минут",ruleNumber:"2.55",ruleFull:"Запрещается багоюз с анимацией — | Jail 120 минут",hint:"Использование ошибок"},
        {id:8,type:"multiple",question:"Что запрещает правило 2.21?",options:["Обход игровой системы","Нецензурные слова","Продажа валюты","Реклама"],correct:0,ruleNumber:"2.21",ruleFull:"Запрещено обходить систему и использовать баги — | Warn/Ban 15-30 дней/PermBan",punishment:"Warn/Ban/PermBan",hint:"Читы и баги"},
        {id:9,type:"text",question:"Максимум аккаунтов на сервере?",correctAnswers:["3","три","максимум 3"],ruleNumber:"4.04",ruleFull:"Разрешается создать максимально 3 аккаунта",hint:"Число меньше 5"},
        {id:10,type:"multiple",question:"За что PermBan + ЧСП?",options:["Деструктивные действия","Первый DM","Одно использование транслита","Первое нарушение"],correct:0,ruleNumber:"2.40",ruleFull:"Запрещены деструктивные действия — | PermBan + ЧС проекта",punishment:"PermBan + ЧС проекта",hint:"Действия против проекта"},
        {id:11,type:"multiple",question:"Что запрещает правило 2.05?",options:["OOC и IC обманы","NonRP вождение","AFK","Аксессуары"],correct:0,ruleNumber:"2.05",ruleFull:"Запрещены OOC-обманы и IC-обманы с нарушением RP",punishment:"Ban 15-30 дней/PermBan",hint:"Обман игроков"},
        {id:12,type:"text",question:"Наказание за транслит в чате?",correctAnswers:["mute 30","мут 30","30 минут"],ruleNumber:"3.20",ruleFull:"Запрещено использование транслита — | Mute 30 минут",hint:"Русские слова английскими буквами"},
        {id:13,type:"multiple",question:"За что Jail 30 минут?",options:["Нарушение RP процесса","Читы","Продажа валюты","Реклама"],correct:0,ruleNumber:"2.01",ruleFull:"Нарушение Role Play процесса — | Jail 30 минут",punishment:"Jail 30 минут",hint:"RP нарушение"},
        {id:14,type:"punishment",question:"Caps Lock в чате - какое наказание?",options:["Jail","Mute","Ban","Warn"],correctPunishments:["Mute"],additionalText:"30 минут",ruleNumber:"3.02",ruleFull:"Запрещено ИСПОЛЬЗОВАНИЕ ВЕРХНЕГО РЕГИСТРА — | Mute 30 минут",hint:"Касается чата"},
        {id:15,type:"multiple",question:"Что такое NonRP Drive?",options:["Вождение в невозможных условиях","Убийство","AFK","Нецензурные слова"],correct:0,ruleNumber:"2.03",ruleFull:"Запрещён NonRP Drive — вождение в невозможных условиях",punishment:"Jail 30 минут",hint:"Невозможное вождение"},
        {id:16,type:"text",question:"Наказание за продажу аккаунта?",correctAnswers:["permban","пермбан","навсегда"],ruleNumber:"4.03",ruleFull:"Передача аккаунта третьим лицам — | PermBan",hint:"Самое строгое наказание"},
        {id:17,type:"multiple",question:"Что запрещает правило 2.28?",options:["Покупка валюты за деньги","Использование транспорта","Нахождение в семьях","Скины"],correct:0,ruleNumber:"2.28",ruleFull:"Запрещена покупка/продажа валюты за реальные деньги — | PermBan",punishment:"PermBan",hint:"Реальные деньги"},
        {id:18,type:"multiple",question:"За оскорбление родных?",options:["Mute 300 минут / Ban 7-15 дней","Jail 30 минут","Mute 30 минут","Warn"],correct:0,ruleNumber:"3.04",ruleFull:"Оскорбление родных — | Mute 300 минут / Ban 7-15 дней",punishment:"Mute 300 минут/Ban 7-15 дней",hint:"Тяжелое нарушение"},
        {id:19,type:"text",question:"Наказание за Flood (3+ одинаковых)?",correctAnswers:["mute 30","30 минут","мут 30"],ruleNumber:"3.05",ruleFull:"Запрещён флуд — | Mute 30 минут",hint:"Спам в чате"},
        {id:20,type:"multiple",question:"Формат игрового никнейма?",options:["Имя_Фамилия на английском","Любой на русском","Только цифры","Произвольный"],correct:0,ruleNumber:"4.06",ruleFull:"Никнейм должен быть в формате 'Имя_Фамилия' на английском",punishment:"Замечание",hint:"Например: John_Doe"}
    ],
    admin: [
        {id:101,type:"multiple",question:"Основная обязанность администратора?",options:["Контроль процесса","Заработок денег","Развлечение","Покупка имущества"],correct:0,ruleNumber:"1.02",ruleFull:"Контроль всего ролевого игрового процесса и помощь игрокам",punishment:"N/A",hint:"Контроль сервера"},
        {id:102,type:"multiple",question:"Может ли админ владеть бизнесом?",options:["Нет, запрещено","Да, любым","Только не АЗС","На одном аккаунте"],correct:0,ruleNumber:"2.04",ruleFull:"Администратору запрещено владеть игровым бизнесом",punishment:"N/A",hint:"Конфликт интересов"},
        {id:103,type:"text",question:"Сколько дней отпуска админу?",correctAnswers:["по согласованию","не указано","зависит"],ruleNumber:"1.05",ruleFull:"Имеет право на отпуск с одобрения главного администратора",hint:"По согласованию"},
        {id:104,type:"multiple",question:"Что такое выговор админу?",options:["Система препятствующая повышению","Устное замечание","Блокировка аккаунта","Снижение зарплаты"],correct:0,ruleNumber:"1.06",ruleFull:"Система выговоров препятствует повышению",punishment:"N/A",hint:"Штрафная система"},
        {id:105,type:"multiple",question:"Админ может препятствовать игрокам?",options:["Нет, ООС персонаж","Да, всё что угодно","Только в особых случаях","Только во время событий"],correct:0,ruleNumber:"1.08",ruleFull:"Администратор ООС персонаж, не может препятствовать RP",punishment:"N/A",hint:"Вне игровой персонаж"},
        {id:106,type:"multiple",question:"Иерархия администрации?",options:["Спец.админ > Гл.админ > Админ > Модератор > Мл.модератор","Модератор > Админ > Спец.админ","Все равны","Мл.модератор > Модератор > Админ"],correct:0,ruleNumber:"1.10",ruleFull:"Строгая иерархия: Спец.админ > Зам.спец > Гл.админ > ...",punishment:"N/A",hint:"От высшего к низшему"},
        {id:107,type:"text",question:"Как долго хранить доказательства?",correctAnswers:["3 дня","три дня","3"],ruleNumber:"3.07",ruleFull:"Администратор обязан хранить доказательства 3 дня",hint:"Меньше недели"},
        {id:108,type:"multiple",question:"Админ может разглашать инфо?",options:["Нет, запрещено","Да, любую","Только игрокам","Только модерам"],correct:0,ruleNumber:"3.13",ruleFull:"Администратору запрещено разглашать внутреннюю информацию",punishment:"N/A",hint:"Конфиденциально"},
        {id:109,type:"punishment",question:"За что админ получает выговор?",options:["Выговор","Kick","Ban","Mute"],correctPunishments:["Выговор"],additionalText:"Система выговоров",ruleNumber:"1.06",ruleFull:"Система выговоров для администраторов",hint:"Штраф для админов"},
        {id:110,type:"multiple",question:"На каком аккаунте имущество админа?",options:["На основном","На любом","На твинке","Не разрешено"],correct:0,ruleNumber:"2.02",ruleFull:"Имущество только на основном аккаунте",punishment:"N/A",hint:"Основной аккаунт"},
        {id:111,type:"text",question:"Дней восстановления мл.модератора?",correctAnswers:["30 дней","30","месяц"],ruleNumber:"3.26",ruleFull:"Мл.модератор может восстановиться в течение 30 дней",hint:"Меньше 90"},
        {id:112,type:"multiple",question:"Админ в семьях игроков?",options:["Нет, запрещено","Да, в любой","Только своей","Только гл.админ"],correct:0,ruleNumber:"3.29",ruleFull:"Администратору запрещено находиться в семьях",punishment:"N/A",hint:"Избегание конфликта"},
        {id:113,type:"multiple",question:"Админ может работать?",options:["Нет, запрещено","Да, везде","Только ночью","Только в начале"],correct:0,ruleNumber:"3.25",ruleFull:"Администрации запрещено работать на игровых работах",punishment:"N/A",hint:"Не зарабатывать валюту"},
        {id:114,type:"text",question:"Админ может менять ник?",correctAnswers:["нет","запрещено","не может"],ruleNumber:"3.15",ruleFull:"Занимая должность запрещено менять игровой ник",hint:"Правило безопасности"},
        {id:115,type:"multiple",question:"Снимать наказания других админов?",options:["Нет, только гл.админ","Да, любой","Только в крайнем","Если согласен игрок"],correct:0,ruleNumber:"3.02",ruleFull:"Запрещено снимать наказания других администраторов",punishment:"N/A",hint:"Субординация"},
        {id:116,type:"multiple",question:"Админ создавать контент?",options:["С согласования гл.админа","Нет, запрещено","Да, без согласования","Только если блогер"],correct:0,ruleNumber:"3.33",ruleFull:"Нужно согласование с главным администратором",punishment:"N/A",hint:"Требует согласования"},
        {id:117,type:"text",question:"На скольких серверах должность?",correctAnswers:["один","одном","на одном"],ruleNumber:"3.19",ruleFull:"Запрещено занимать должности на других проектах",hint:"Конфликт интересов"},
        {id:118,type:"multiple",question:"Что означает ООС для админа?",options:["Вне ролевой персонаж","Главная роль","Может использовать читы","Максимум денег"],correct:0,ruleNumber:"1.08",ruleFull:"Администратор ООС персонаж - вне игровой роли",punishment:"N/A",hint:"Out of Character"},
        {id:119,type:"punishment",question:"Защита аккаунта админа?",options:["2FA","Пароль","PIN","Email"],correctPunishments:["2FA"],additionalText:"Двухфакторная",ruleNumber:"3.32",ruleFull:"Установить дополнительную защиту (2FA)",hint:"Двухфакторная аутентификация"},
        {id:120,type:"multiple",question:"Админ передавать ценности?",options:["Нет, без причины запрещено","Да, всё что угодно","Только деньги","Только транспорт"],correct:0,ruleNumber:"3.17",ruleFull:"Запрещено передавать ценности без причины",punishment:"N/A",hint:"Нейтральность администратора"}
    ],
    rp: [
        {id:201,type:"multiple",question:"Что означает DM?",options:["Убийство без причины","Быстрая езда","Читы","AFK"],correct:0,ruleNumber:"РП Термин 1",ruleFull:"DM [DeathMatch] - Убийство без причины",punishment:"Jail 90 минут",hint:"Death Match"},
        {id:202,type:"multiple",question:"Что такое DB (DriveBy)?",options:["Убийство машиной/из машины","Быстрая езда","Парковка","Огни"],correct:0,ruleNumber:"РП Термин 2",ruleFull:"DB [DriveBy] - Убийство машиной или из машины",punishment:"Warn",hint:"Drive By"},
        {id:203,type:"text",question:"Наказание за RK (RevengeKill)?",correctAnswers:["warn","варн","варни"],ruleNumber:"РП Термин RK 2",ruleFull:"RK [RevengeKill] - Убийство в отместку",hint:"Первое нарушение"},
        {id:204,type:"multiple",question:"Что означает SK?",options:["Убийство при спавне","Скорость","Специальный ключ","Система килла"],correct:0,ruleNumber:"РП Термин 3",ruleFull:"SK [SpawnKill] - Убийство при появлении персонажа",punishment:"Warn",hint:"Spawn - появление"},
        {id:205,type:"multiple",question:"Что такое RolePlay?",options:["Отыгрывание роли в игре","Использование читов","Быстрый заработок","Трансляция"],correct:0,ruleNumber:"РП Термин 4",ruleFull:"RP [RolePlay] - Отыгрывание роли",punishment:"N/A",hint:"Role Play"},
        {id:206,type:"text",question:"Расшифруй ЗЗ:",correctAnswers:["green zone","зеленая зона","gz"],ruleNumber:"РП Термин 5",ruleFull:"ЗЗ [GreenZone] - Зелёная зона",hint:"Безопасная территория"},
        {id:207,type:"multiple",question:"Что означает ГМ?",options:["Режим Бога","Хорошая игра","Группа игроков","Главный модератор"],correct:0,ruleNumber:"РП Термин 10",ruleFull:"ГМ [GodMode] - Режим Бога (неуязвимость)",punishment:"Ban 15-30 дней",hint:"God Mode"},
        {id:208,type:"multiple",question:"Что такое MG?",options:["Использование OOC инфо в IC","Быстрый заработок","Множественная игра","Главное меню"],correct:0,ruleNumber:"РП Термин 12",ruleFull:"MG [MetaGaming] - Использование OOC информации",punishment:"Ban 15-30 дней",hint:"Meta Gaming"},
        {id:209,type:"text",question:"Что означает ФР?",correctAnswers:["фаст резарядка","fast reload","быстрая перезарядка"],ruleNumber:"РП Термин 16",ruleFull:"ФР - Баг с быстрой перезарядкой",hint:"Fast Reload"},
        {id:210,type:"multiple",question:"Что означает ОРП?",options:["Уход от role play","Офис руководства","Открытие рабочего","Основной регистр"],correct:0,ruleNumber:"РП Термин 23",ruleFull:"ОРП - Уход от Role Play",punishment:"Jail 30 минут",hint:"Out of RolePlay"}
    ]
};

function getQuestions(category = 'all') {
    if (category === 'all') {
        return [...questionsDatabase.server, ...questionsDatabase.admin, ...questionsDatabase.rp];
    }
    return questionsDatabase[category] || [];
}